"""empty message

Revision ID: 1d0f980a6eb2
Revises: 8311e927c069
Create Date: 2024-10-20 15:25:46.921998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d0f980a6eb2'
down_revision = '8311e927c069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('state',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
