"""Added pulled column to athlete table, checks if records have been pulled for certification

Revision ID: e67fdc0d17ae
Revises: 1d0f980a6eb2
Create Date: 2025-02-23 14:19:17.718486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e67fdc0d17ae'
down_revision = '1d0f980a6eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=True)

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pulled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_column('pulled')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('state',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
